_project/urls.py
from django.contrib import admin
from django.urls import path, include
# from user import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include("user.urls")),
    path('movie/', include('movie.urls')),  # Include the app's urls.py here

]

movie/urls.py
from django.urls import path, include
from . import views
 path("logout/" , LogoutView.as_view(next_page = "movie:dashboard")),# from movie import urls
app_name = 'movie'

urlpatterns = [
    
    path("",views.dashboard , name= 'dashboard' ),
    path("logout/" , LogoutView.as_view(next_page = "movie:dashboard")),
    path("showtime/<int:id>" , views.showtime_view  ,name = "showtime"),
    path("reser/<int:id>", views.res_view, name ="reservation" )
]

user/urls.py
from django.urls import path, include
from movie import urls
from . import views
app_name = "user"

urlpatterns = [
    path("register/", views.register , name= "register"),
    path("login/", views._login, name="login"),
    # path('movie/', include('movie.urls')),  # Include the app's urls.py here

    
    
]

movie/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Movie(models.Model):
    title = models.CharField( max_length=50)
    des = models.CharField( max_length=50)
    durtion = models.DurationField()
    
    def __str__(self):
        return self.title
    
    
class ShowTime(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    start_time = models.DateTimeField( auto_now=False, auto_now_add=False)
    total_seats = models.IntegerField()
    
    def __str__(self):
        return f"{self.movie.title} - {self.start_time}  "
    
    
class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    show_time = models.ForeignKey(ShowTime, on_delete=models.CASCADE)
    seat_no = models.IntegerField()
    
    
    def __str__(self):
        return f"{self.user.username} - {self.show_time.movie.title} - {self.show_time.start_time} - {self.seat_no}"
    
    
    
    

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class Custom_UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email',"first_name","last_name", 'password1', 'password2' , 'is_staff']

movie/views.py
from django.shortcuts import render,  get_object_or_404 , redirect, reverse
from .models import Movie, Reservation, ShowTime
# Create your views here.

def dashboard(request):
    if request.user.is_authenticated:
        
        movie = Movie.objects.all()
        reser = Reservation.objects.filter(user = request.user)
        
        if request.method == "POST":
            reservation_id = request.POST.get("reser_id")
            # print(reservation_id)
            reservation = Reservation(user=request.user, id = reservation_id )
            reservation.delete()
            
        
        return render(request, "dashboard.html", {"movie": movie, "reser":reser})
    else:
        return redirect("user:login")

 



def showtime_view (request, id):
    
    if request.user.is_authenticated:  
        movie = Movie.objects.get(id = id)
        print(movie)
        shows =  ShowTime.objects.filter(movie=movie)
        
        print (shows)
        print(shows)
        return render (request, "showtime.html", {"shows": shows} )
    else:
        return redirect("user:login")
    








def res_view(request,id):
    if request.user.is_authenticated:  
        shows = ShowTime.objects.get(id = id)
        reser =  Reservation.objects.filter(show_time= shows)
        total_seats = shows.total_seats
        
        # print(request.user)
        # print(reser)
        # for r in reser:
        #     print(r.user)
        
        booked_seat_no = [reservation.seat_no for reservation in reser]
        
        ur_reser = Reservation.objects.filter(show_time = shows, user= request.user)
        print(ur_reser)
        
        total_booked_seats =  0
        
        for r in reser:
            total_booked_seats += 1      
            
        available_seats = total_seats - total_booked_seats
        
      
        ur_reser_seats = [reservation.seat_no for reservation in ur_reser]
        print (ur_reser_seats)
        print (booked_seat_no)
        
        
        total_seats_range =    range(1, total_seats +1)
        
        
        
        
        if request.method == 'POST':
            seat_no = request.POST.get('seat_no')
            if seat_no  not in booked_seat_no:
                Reservation.objects.create(user= request.user, show_time = shows, seat_no = seat_no)
                return redirect(reverse("movie:reservation", kwargs={'id': id}))
        
        return render (request, "reservation.html", {
            "reser": reser, 
            "total_seats": total_seats, 
            "total_seats_range":total_seats_range,
            "total_booked_seats": total_booked_seats,
            "booked_seat_no": booked_seat_no,
            "available_seats":available_seats,
            "ur_reser": ur_reser,
            "ur_reser_seats": ur_reser_seats})
        
        
    else:
        return redirect("user:login")
    
    

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate
from .forms import Custom_UserCreationForm

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = Custom_UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            print ("register successfully")
            return redirect('user:login')
    else:
        form = Custom_UserCreationForm()
    return render(request, 'register.html', {'form': form})



def _login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            
            user = authenticate(username = username, password= password)
            
            if user is not None:
                login(request, user)
                return redirect('movie:dashboard')
            
            else : 
                pass
        else:
            print(ValueError)
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

movie/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    
    <h1>
        Hello User 
    </h1>

    <div>

        {% if request.user.is_authenticated %}

        
        <label for="" style="padding: 5px;"> Hi {{user.username}}  {{user.first_name}}  {{user.last_name}} </label>
        <a href="logout">
            <button style="width: 200px; height: 30px; padding: 5px; ">logout</button>
        </a>
        <br><br><br><br>

        {% for movie in movie  %}

        <a href="{% url 'movie:showtime' movie.id %}">{{movie.title}}</a>
        <br><br>
        
        {% endfor %}

        <br><br><br><br>

        <h2>Your Reservation</h2>

        
        {% for reser in reser  %}
        
        <form method="post" >
        {% csrf_token %}
        <p>
            
                Movie Name:   <b>{{reser.show_time.movie.title}}</b>  <br>
                Movie Date:  <b>{{reser.show_time.start_time}} </b> 
                &nbsp;&nbsp;&nbsp;&nbsp;
                
                <button type="submit" name="reser_id" value="{{reser.id}}"> Cancel Seat</button>
                <br>

                Your Seat No:  <b>{{reser.seat_no}}</b> 
                <br><br>
                

        </p>    
         </form>
        {% endfor %}

         {%else%}

        <a href=" {% url 'user:register' %} ">
            <button style="width: 200px; height: 30px; padding: 5px; " >Register</button>
        </a>

        <a href=" {% url 'user:login' %} ">
            <button style="width: 200px; height: 30px; padding: 5px; ">login</button>
        </a> 

        {%endif%}
      
    </div>

</body>
</html>

movie/templates/reservation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   
    <h1>Already reserved Seats </h1>

     <div>
        <b>
        total seats are {{total_seats}}
        </b>
    </div>
    <br><br>

    {% for reservation in reser  %}
    
    {% comment %} <li>{{reser}}</li> {% endcomment %}
    <div>
        <p>
            For Movie <b>{{reservation.show_time.movie.title}} </b> at time <b>{{reservation.show_time.start_time}}</b> Seat Number  <b>{{ reservation.seat_no }}</b> is Booked
        </p>
    </div>
    
    {% endfor %}


    <br><br>

    <h3>Available seats are only {{available_seats}}</h3>

     <form method="post" >
        {% csrf_token %}
        {% for seat in total_seats_range %}
        
            {% if seat in booked_seat_no %}

                {% if  seat in ur_reser_seats %}
                        <button type="button" class="booked" disabled style="background-color: blue;">Seat No {{ seat }} </button>

                {% else %}
                 <button type="button" class="booked" disabled style="background-color: red;">Seat No {{ seat }} </button>


                    {% endif %}
               
               

            {% else %}
                <button type="submit" name="seat_no" value="{{ seat }}">Seat No {{ seat }}</button>
            {% endif %}
        {% endfor %}



        



        
        

    </form>


    <br><br>

    <h2>Your Reservation</h2>

    {% for ur_reser in ur_reser %}
    
    <p>
        {{ur_reser}} Seat Number {{ur_reser.seat_no}}
    </p>

    {% endfor %}

</body>
</html>

movie/templates/showtime.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show Time</title>
</head>
<body>
    <h1> {{shows.movie.title}} </h1>

    {% for shows in shows %}

    
    
    <div>
        <a href="{% url 'movie:reservation' shows.id %}">{{shows}}</a>
    </div>

    {% endfor %}

    
</body>
</html>

user/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>User Login</title>
</head>
<body>
    <h2>User Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</body>
</html>

user/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>User Registration</title>
</head>
<body>
    <h2>User Registration</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</body>
</html>